---
title: "Homework Week 02"
author: "Md Ariful Haque Miah"
date: "9/11/2022"
output: pdf_document
---
```{r}
getwd()
Machine <- c("Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2")
dat <- c(16.03,16.04,16.05,16.05,16.02,16.01,15.96,15.98,16.02,15.99,16.02,15.97,15.96,16.01,15.99,16.03,16.04,16.02,16.01,16.00)
length(Machine)
length(dat)
str(Machine)
Machine <- as.factor(Machine)
str(Machine)
str(dat)
dat1 <- data.frame(Machine,dat)
dat1
# Answer to the problem No: 2.24.(a)
# Hypotheses Statement:
# H0: u1 = u2 or u1-u2 = 0
# Ha: u1 != u2 or u1 -u2 != 0

# Answer to the problem No: 2.24.(b)
library(dplyr)
dat2 <- dat1 %>% filter(Machine=="Machine 1") %>% select(dat)
dat3 <- dat1 %>% filter(Machine=="Machine 2") %>% select(dat)
t.test(dat2,dat3,var.equal = TRUE)
# p value > 0.05 so we fail to reject H0. Hence, the mean is equal so the both 
# machines fill to the same net volume regardless of the volume is 16.0 ounce at the 
# alpha = 0.05 level of significance and the quality engineering department's suspect is true.

# Answer to the problem No: 2.24.(c)
# P-value for this test is 0.4347

# Answer to the problem No: 2.24.(d)
# 95 percent confidence interval on the difference in the mean fill volume for 
# the two machines are
#  -0.01629652<= u1-u2 <=0.03629652

# Answer to the problem No: 2.26
Type <- c("Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2")
dat4 <- c(65,81,57,66,82,82,67,59,75,70,64,71,83,59,65,56,69,74,82,79)
str(Type)
Type <- as.factor(Type)
str(Type)
str(dat4)
dat5 <- data.frame(Type,dat4)
dat5

# Answer to the problem No: 2.26.(a)
library(lawstat)
levene.test(dat5$dat4,dat5$Type,location="mean")
# Hence, P value > 0.05, so we fail to reject H0 and therefore the variance's are equal
# at alpha = 0.05 level of significance.

# Answer to the problem No: 2.26.(b)
# From the results of (a), we see that variance's are equal. Hence we can use 
# Two Sample t test with pooled variance to test the hypotheses.
# Hypotheses Statement:
# H0: u1 = u2 or u1-u2 = 0
# Ha: u1 != u2 or u1 -u2 != 0
library(dplyr)
dat6 <- dat5 %>% filter(Type=="Type1") %>% select(dat4)
dat7 <- dat5 %>% filter(Type=="Type2") %>% select(dat4)
t.test(dat6,dat7,var.equal = TRUE)
# Hence, P value > 0.05, so we fail to reject H0 and therefore the mean burning times
# are equal at alpha = 0.05 level of significance.
# P-value for this test is 0.9622.

# Answer to the problem No: 2.29
Temp95 <- c(11.176,7.089,8.097,11.739,11.291,10.759,6.467,8.315)
Temp100 <- c(5.263,6.748,7.461,7.015,8.133,7.418,3.772,8.963)
dat8 <- data.frame(Temp100,Temp95)
dat8

# Answer to the problem No: 2.29.(a)
# Hypotheses Statement:
# H0: u1 (mean of Temp 100) = u2 (mean of Temp 95) or u1-u2 = 0
# Ha: u1 (mean of Temp 100) < u2 (mean of Temp 95)
# Two sample t test is as follows:
t.test(Temp100,Temp95,var.equal = TRUE,alternative = "less")
# Since P-value < 0.05 at a alpha = 0.05 level of significance so we reject H0
# Thus, there is evidence to support the claim that higher the baking temperature
# results with a lower mean photo resist thickness.

# Answer to the problem No: 2.29.(b)
# P-value for the test conducted in part (a) is 0.009059.

# Answer to the problem No: 2.29.(c)
# 95% confidence interval on the difference in mean is 
# -infinity <= u1-u2 <= -0.8608158
# This confidence interval does not include 0 in it. So, there is a difference 
# in the two temperatures on the thickness of the photo resist.

# Answer to the problem No: 2.29.(e)
# Normality assumptions check
qqnorm(dat8$Temp100,main="Normal Probability Plot Temp100",col="blue",ylab="100 degree celcius")
qqline(dat8$Temp100)
qqnorm(dat8$Temp95,main="Normal Probability Plot Temp95",col="red",ylab="95 degree celcius")
qqline(dat8$Temp95)
# No significant deviations been observed from both (Temp 100 and Temp 95) of the 
# the normality assumptions.
```
Source Code
```{r eval=FALSE}
getwd()
Machine <- c("Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 1","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2","Machine 2")
dat <- c(16.03,16.04,16.05,16.05,16.02,16.01,15.96,15.98,16.02,15.99,16.02,15.97,15.96,16.01,15.99,16.03,16.04,16.02,16.01,16.00)
length(Machine)
length(dat)
str(Machine)
Machine <- as.factor(Machine)
str(Machine)
str(dat)
dat1 <- data.frame(Machine,dat)
dat1
library(dplyr)
dat2 <- dat1 %>% filter(Machine=="Machine 1") %>% select(dat)
dat3 <- dat1 %>% filter(Machine=="Machine 2") %>% select(dat)
t.test(dat2,dat3,var.equal = TRUE)
Type <- c("Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type1","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2","Type2")
dat4 <- c(65,81,57,66,82,82,67,59,75,70,64,71,83,59,65,56,69,74,82,79)
str(Type)
Type <- as.factor(Type)
str(Type)
str(dat4)
dat5 <- data.frame(Type,dat4)
dat5
library(lawstat)
levene.test(dat5$dat4,dat5$Type,location="mean")
library(dplyr)
dat6 <- dat5 %>% filter(Type=="Type1") %>% select(dat4)
dat7 <- dat5 %>% filter(Type=="Type2") %>% select(dat4)
t.test(dat6,dat7,var.equal = TRUE)
Temp95 <- c(11.176,7.089,8.097,11.739,11.291,10.759,6.467,8.315)
Temp100 <- c(5.263,6.748,7.461,7.015,8.133,7.418,3.772,8.963)
dat8 <- data.frame(Temp100,Temp95)
dat8
t.test(Temp100,Temp95,var.equal = TRUE,alternative = "less")
qqnorm(dat8$Temp100,main="Normal Probability Plot Temp100",col="blue",ylab="100 degree celcius")
qqline(dat8$Temp100)
qqnorm(dat8$Temp95,main="Normal Probability Plot Temp95",col="red",ylab="95 degree celcius")
qqline(dat8$Temp95)
```

